soundlist_xylo = ['../PlayPercussions/Sounds/Xylophon/Xylophon f0.wav',
                  '../PlayPercussions/Sounds/Xylophon/Xylophon g0.wav',
                  '../PlayPercussions/Sounds/Xylophon/Xylophon a0.wav',
                  '../PlayPercussions/Sounds/Xylophon/Xylophon b0.wav',
                  '../PlayPercussions/Sounds/Xylophon/Xylophon c1.wav',
                  '../PlayPercussions/Sounds/Xylophon/Xylophon d1.wav',
                  '../PlayPercussions/Sounds/Xylophon/Xylophon e1.wav',
                  '../PlayPercussions/Sounds/Xylophon/Xylophon f1.wav',
                  '../PlayPercussions/Sounds/Xylophon/Xylophon g1.wav',
                  '../PlayPercussions/Sounds/Xylophon/Xylophon a1.wav',
                  '../PlayPercussions/Sounds/Xylophon/Xylophon b1.wav',
                  '../PlayPercussions/Sounds/Xylophon/Xylophon c2.wav',
                  '../PlayPercussions/Sounds/Xylophon/Xylophon d2.wav',
                  '../PlayPercussions/Sounds/Xylophon/Xylophon e2.wav',
                  '../PlayPercussions/Sounds/Xylophon/Xylophon f2.wav',
                  '../PlayPercussions/Sounds/Xylophon/Xylophon g2.wav',
                  '../PlayPercussions/Sounds/Xylophon/Xylophon a2.wav',
                  '../PlayPercussions/Sounds/Xylophon/Xylophon b2.wav',
                  '../PlayPercussions/Sounds/Xylophon/Xylophon c3.wav',
                  '../PlayPercussions/Sounds/Xylophon/Xylophon d3.wav',
                  '../PlayPercussions/Sounds/Xylophon/Xylophon e3.wav',
                  '../PlayPercussions/Sounds/Xylophon/Xylophon f3.wav', ]

soundlist_xylo_accidental = ['../PlayPercussions/Sounds/Xylophon/Xylophon f#0.wav',
                             '../PlayPercussions/Sounds/Xylophon/Xylophon g#0.wav',
                             '../PlayPercussions/Sounds/Xylophon/Xylophon a#0.wav',
                             '../PlayPercussions/Sounds/Xylophon/Xylophon c#1.wav',
                             '../PlayPercussions/Sounds/Xylophon/Xylophon d#1.wav',
                             '../PlayPercussions/Sounds/Xylophon/Xylophon f#1.wav',
                             '../PlayPercussions/Sounds/Xylophon/Xylophon g#1.wav',
                             '../PlayPercussions/Sounds/Xylophon/Xylophon a#1.wav',
                             '../PlayPercussions/Sounds/Xylophon/Xylophon c#2.wav',
                             '../PlayPercussions/Sounds/Xylophon/Xylophon d#2.wav',
                             '../PlayPercussions/Sounds/Xylophon/Xylophon f#2.wav',
                             '../PlayPercussions/Sounds/Xylophon/Xylophon g#2.wav',
                             '../PlayPercussions/Sounds/Xylophon/Xylophon a#2.wav',
                             '../PlayPercussions/Sounds/Xylophon/Xylophon c#3.wav',
                             '../PlayPercussions/Sounds/Xylophon/Xylophon d#3.wav']

soundlist_bongos = ['../PlayPercussions/Sounds/Bongos/Bongo_high.wav',
                    '../PlayPercussions/Sounds/Bongos/Bongo_low.wav']

soundlist_timpani = ['../PlayPercussions/Sounds/Timpani/C#_Timpani.wav',
                     '../PlayPercussions/Sounds/Timpani/G#_Timpani.wav']

soundlist_timbales = ['../PlayPercussions/Sounds/Timbales/HighTimbales.wav',
                      '../PlayPercussions/Sounds/Timbales/LowTimbales.wav',
                      '../PlayPercussions/Sounds/Timbales/Cowbell.wav']

soundlist_steeldrum = ['../PlayPercussions/Sounds/Steeldrum/SteeldrumA4.wav',
                       '../PlayPercussions/Sounds/Steeldrum/SteeldrumE4.wav',
                       '../PlayPercussions/Sounds/Steeldrum/SteeldrumB4.wav',
                       '../PlayPercussions/Sounds/Steeldrum/SteeldrumF#4.wav',
                       '../PlayPercussions/Sounds/Steeldrum/SteeldrumC#4.wav',
                       '../PlayPercussions/Sounds/Steeldrum/SteeldrumG#4.wav',
                       '../PlayPercussions/Sounds/Steeldrum/SteeldrumD#4.wav',
                       '../PlayPercussions/Sounds/Steeldrum/SteeldrumA#4.wav',
                       '../PlayPercussions/Sounds/Steeldrum/SteeldrumF4.wav',
                       '../PlayPercussions/Sounds/Steeldrum/SteeldrumC4.wav',
                       '../PlayPercussions/Sounds/Steeldrum/SteeldrumG4.wav',
                       '../PlayPercussions/Sounds/Steeldrum/SteeldrumD4.wav']
